export const layerStyles = {
    card: {
        p: 8,
        borderWidth: 1,
        borderRadius: 4,
        boxShadow: 'lg',
    },
    credentialsCard: {
        p: 8,
        borderWidth: 1,
        borderRadius: 4,
        boxShadow: 'lg',
        width: ['274px', '360px'],
    },
    nutrient: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        py: 2,
        borderRadius: 4,
        boxShadow: 'lg',
        fontWeight: '900',
        color: 'white',
    },
    colorfulCard: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 4,
        boxShadow: 'lg',
        fontWeight: '900',
        color: 'white',
    },
    fracNumerator: {
        float: 'left',
    },
    fracDenominator: {
        borderTop: 'solid',
        clear: 'left',
        float: 'left',
    },
    navBar: {
        bg: '#3db9a2',
        height: '84px',
        padding: '0px 40px',
        boxShadow: 'lg',
    },
    tabContentTitle: {
        color: 'pageGreen.500',
        fontSize: ['28px', '28px', '35px', '50px'],
        fontWeight: '700',
    },
    tabContentSubTitle: {
        color: 'pageGreen.400',
        fontSize: ['14px', '14px', '18px', '25px'],
        fontWeight: '700',
        mb: '20px',
    },
    mealTabSummaryTitle: {
        color: 'pageGreen.500',
        fontSize: ['14px', '16px', '20px', '25px'],
        fontWeight: '700',
        textAlign: 'left',
    },
    mealTabSummarySubTitle: {
        color: 'gray.500',
        fontSize: ['10px', '12px', '16px', '20px'],
        fontWeight: '700',
        textAlign: 'left',
    },
    searchInterface: {
        position: 'relative',
        h: 'full',
        borderStyle: 'none solid solid solid',
        borderWidth: '3px',
        borderColor: 'pageGreen.500',
    },
    searchResultList: {
        m: '20px 5px 5px 5px',
    },
};
